#Rutina para simular la fuente de datos que almacena datos de los gastos
#id
#fecha "2026-05-06"
#monto
#descripcion

#TAREA: PROGRAME AQUI FUNCION GENERADORA DE GASTOS SIMULADOS

#TAREA: PROGRAMAR RUTINA PARA INYECTAR ERRORES CONTROLADOS EN LSO CAMPOS ID,FECHA,MONTO,DESCRIPCION
